---
title: "Teaching"
format: html
---
## My philosophy 
My teaching philosophy is tied to my research in health, science, and environmental communication, beginning with a rejection of the deficit model. The deficit model assumes that experts hold authoritative knowledge, while audiences (or students, in this case) are passive recipients for information. Instead, I approach education as a co-constructive process built on dialogue and mutual learning. My goal is not simply to transmit key concepts, theories, and skills, but to help students develop the tools to think critically, build evidence-based arguments, and understand complex issues from multiple perspectives, whether its navigating a public health controversy, crafting a strategic communication campaign, or evaluating an advertising narrative. With teaching experience from elementary school to the university, I'm passionate about helping students of all ages learn how to think.  

## Teaching Experience 

<table style="width:100%; border:none;">
  <tr style="border:none;">
    <td style="width:40%; vertical-align:top; border:none;">
      **Fall 2025** <br>
      <small style="color:gray;">Cornell University</small>
    </td>
    <td style="vertical-align:top; border:none;">
      **Teaching Assistant** — Communication and Technology <br>
      <small style="color:gray;">Supported 60 undergraduates through grading, office hours, and one-on-one meetings; contributed to exam design and managed course email site.</small>
    </td>
  </tr>
  <tr style="border:none;">
    <td style="width:20%; vertical-align:top; border:none;">
      **Summer 2025** <br>
      <small style="color:gray;">Cornell University</small>
    </td>
    <td style="vertical-align:top; border:none;">
      **Instructor of Record** — Communication, Environment, Science, and Health <br>
      <small style="color:gray;">Designed and instructed a 6-week online course for 15 undergraduates, including syllabus development, lecture design and delivery, review sessions, and all grading.</small>
    </td>
    </tr>
  <tr style="border:none;">
    <td style="width:30%; vertical-align:top; border:none;">
      **Spring 2024** <br>
      <small style="color:gray;">Lehman Alternative Community School</small>
    </td>
    <td style="vertical-align:top; border:none;">
      **Teaching Fellow** — Whose Knowledge Counts? Navigating the Science, Politics, and Ethics of Saving Our Planet Through Place-Based Knowledge Systems <br>
      <small style="color:gray;">Co-designed and delivered a 3-lesson curriculum for 10th graders on how knowledge from diverse cultures shapes environmental decision-making; coordinated with classroom teacher to ensure alignment with New York State learning standards and developed interactive, discussion-based lessons.</small>
    </td>
  </tr>
  <tr style="border:none;">
    <td style="width:20%; vertical-align:top; border:none;">
      **Summer 2023** <br>
      <small style="color:gray;">Cornell University</small>
    </td>
    <td style="vertical-align:top; border:none;">
      **Instructor of Record** — Communication, Environment, Science, and Health <br>
      <small style="color:gray;">Designed and instructed a 3-week online course for 5 undergraduates, including syllabus development, lecture design and delivery, review sessions, and all grading.</small>
    </td>
      </tr>
  <tr style="border:none;">
    <td style="width:30%; vertical-align:top; border:none;">
      **Spring 2023** <br>
      <small style="color:gray;">Belle Sherman Elementary School</small>
    </td>
    <td style="vertical-align:top; border:none;">
      **Teaching Fellow** — Discovering Nature and Art in Everyday Life <br>
      <small style="color:gray;">Co-designed and delivered a 3-lesson curriculum for 3rd and 4th graders on basic plant identification, plant pressing, and cyanotype sunprints; coordinated with classroom teacher to ensure alignment with New York State learning standards and developed interactive, discussion-based lessons.</small>
    </td>
      </tr>
  <tr style="border:none;">
    <td style="width:20%; vertical-align:top; border:none;">
      **Spring 2023** <br>
      <small style="color:gray;">Cornell University</small>
    </td>
    <td style="vertical-align:top; border:none;">
      **Teaching Assistant** — Communication, Environment, Science, and Health <br>
      <small style="color:gray;">DSupported 50 undergraduates through grading, office hours, and one-on-one advising; contributed to assignment and exam design and delivered guest lectures.</small>
    </td>
  </tr>
  <tr style="border:none;">
    <td style="width:30%; vertical-align:top; border:none;">
      **Fall 2022** <br>
      <small style="color:gray;">Cornell University</small>
    </td>
    <td style="vertical-align:top; border:none;">
      **Teaching Assistant** — Communication and Technology <br>
      <small style="color:gray;">Supported 55 undergraduates through grading, office hours, and one-on-one meetings; contributed to assignment and exam design.</small>
    </td>
    </tr>
  <tr style="border:none;">
    <td style="width:30%; vertical-align:top; border:none;">
      **Fall 2021 - Spring 2022** <br>
      <small style="color:gray;">Geschwister Scholl Realschule</small><br>
      <small style="color:gray;">Andernach, Germany</small>
    </td>
    <td style="vertical-align:top; border:none;">
      **U.S. Fulbright Grantee: Teaching Assistant** — English <br>
      <small style="color:gray;">Fostered community and inclusion at a German secondary school with a significant number of students from refugee and migrant backgrounds. Designed and delivered lessons from American culture, history, and media alongside English grammar, vocabulatry, pronunication, and reading and writing skills. Developed an afterschool English club, creating informal spaces for language practice and community building. 
    </td>
</table>
